name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: Remove .git directory
        run: |
          rm -rf .git
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: |
          npm version patch && npm publish --access public
